//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a DAL.Modellate.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public System.TimeSpan Time { get; set; }
        public int MatchId { get; set; }
        public int PlayerRegNum { get; set; }
        public int EventMessageId { get; set; }
        public int TeamId { get; set; }
    
        public virtual EventMessage EventMessage { get; set; }
        public virtual Match Match { get; set; }
        public virtual Player Player { get; set; }
        public virtual Team Team { get; set; }
    }
}
