//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a DAL.Modellate.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistic
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public short Number { get; set; }
        public int PlayerRegNum { get; set; }
        public int TeamId { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Team Team { get; set; }
    }
}
