//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bll
{
    using System;
    using System.Collections.Generic;
    
    public partial class Update
    {
        public int id { get; set; }
        public string name { get; set; }
        public System.DateTime date { get; set; }
        public int data1 { get; set; }
        public int data2 { get; set; }
        public bool isAdding { get; set; }
    }
}
